@token=

GET http://localhost:8000/preparation-tasks/reminder/
Authorization: Bearer {{token}}

###
POST http://localhost:8000/preparation-tasks/reminder/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Review DSA"
}

###
PATCH http://localhost:8000/preparation-tasks/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Practice DSA"
}


###
PATCH http://localhost:8000/preparation-tasks/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "completed": true
}


###
PATCH http://localhost:8000/preparation-tasks/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "title": "Revise Arrays",
    "completed": false
}


###
DELETE http://localhost:8000/preparation-tasks/
Authorization: Bearer {{token}}

###

POST http://localhost:8000/preparation-ai/test
Authorization: Bearer {{token}}

###
###
POST http://localhost:8000/preparation-ai/reminder//generate
Authorization: Bearer {{token}}