"""add telegram connect tokens table

Revision ID: 10dbabe766ff
Revises: d80e4fbf7000
Create Date: 2026-07-03 17:39:00.914489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10dbabe766ff'
down_revision: Union[str, Sequence[str], None] = 'd80e4fbf7000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_connect_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_connect_tokens_id'), 'telegram_connect_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_connect_tokens_token'), 'telegram_connect_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_connect_tokens_token'), table_name='telegram_connect_tokens')
    op.drop_index(op.f('ix_telegram_connect_tokens_id'), table_name='telegram_connect_tokens')
    op.drop_table('telegram_connect_tokens')
    # ### end Alembic commands ###
