"""added gmail watch exp

Revision ID: 19b2f35a0822
Revises: 591ebdf5c53f
Create Date: 2026-07-03 19:57:25.975050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b2f35a0822'
down_revision: Union[str, Sequence[str], None] = '591ebdf5c53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_watch_expiration', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_watch_expiration')
    # ### end Alembic commands ###
